### Création d'un user
POST http://localhost:4000/signup
Content-Type: application/json

{
  "lastname":"fgdgdfg",
  "firstname":"hhh",
  "pseudo":"sdfsdfs999df",
  "password":"123456789",
  "passwordConfirm":"123456789",
  "email":"t@tgdfgfh.fr"
}