PATCH http://localhost:4000/accounts/mode
Content-Type: application/json

{
  "accountsMode": [
    { "accountId": 1, "mode": "up" },
    { "accountId": 10, "mode": "down" }
  ]
}

###

DELETE http://localhost:4000/user/5

